apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-argocd-k8-app
  labels: 
    app: argocd-k8-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-k8-app
  template:
    metadata:
      name: argocd-k8-app-pod
      labels:
        app: argocd-k8-app
    spec:
      containers:
      - name: argocd-k8-app-container
        image: venu1322/ultimate-cicd:replaceImageTag
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-argo-k8-app
spec:
  type: NodePort
  selector:
    app: argocd-k8-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  


      
